### ISSUE TITLE
Starting late

### ISSUE THREAD

**Issue by tielur** [hueniverse/hueniversity#111]
I just found hueniveristy, is it too late to start joining in on the learning?

**Comment by zoe-1** [comment]
It should be fine to start now.  
Read the git guide https://github.com/hueniverse/hueniversity/blob/master/guides/git.md
to make sure your fork matches the current master. 
Try to complete assignment 3 by 4/14 when we are due to start the next assignment. 
When your assignment is ready make a pull request (PR) to submit your assignment. 
Others will critique your assignment after it has been submitted.

Assignment 3 link below:
https://github.com/hueniverse/hueniversity/issues/79

Also, read the projects Readme file and look over all the linked documents in the Readme. 
(style guide  , Code of Conduct, etc..)

Cheers!

**Comment by tielur** [comment]
@zoe-1 thanks for the help!

**Comment by hueniverse** [comment]
You can start at any time. You should do all the assignments in order and then check the results and comments to compare to your work. Or just read the code accepted and learn from that to catch up. Welcome!
