### ISSUE TITLE
Beginners Prerequisite exam (puzzle?)

### ISSUE THREAD

**Issue by Alayode** [hueniverse/hueniversity#114]
I think it is great if you guys gave some sort of challenge question to help people know what they should know before spending time on this project. I would like to send this to some students of mine but with everyone with varying levels of skill it might not be a good idea. A simple explanation would suffice so I can properly instruct my class on whats expected of them.

**Comment by TheAlphaNerd** [comment]
It is my impression that this course is meant for everyone. Now I would
imagine there is a hard prerequisite in being able to set up a node
environment, and be able to write some basic Javascript. Basics in git are
also necessary to submit work.

Nodeschool.io would be a good place to get started with the basics of js /
node.

If people have questions they should just make an issue, there are quite a
few of us ready to start helping

Now with that being said I can understand that it might be overwhelming or
not preferable to get help in an open forum. My information is publicly
available, feel free to send students to me if they need some guidance

**Comment by AdriVanHoudt** [comment]
I agree with @TheAlphaNerd, basic knowledge of Js and Node is required and maybe how restfull api's work. And like @TheAlphaNerd said, we are here to help (issue here or on the gitter/irc)

**Comment by gyaresu** [comment]
I'd also recommend http://www.freecodecamp.com/ for a place to start learning.
It taps into much of the material available online and is a really good community space.

They have a Slack channel, live coding on Twitch.tv and a clear linear "do all these things" approach to get people up and running with programming in Javascript.

I think this experiment is geared at people who have the basics and are looking for a guide on how to construct real-world apps.

I am currently following the video guide that accompanies http://humanjavascript.com/ which is similar in giving you a clear way to put all the development pieces together rather than just one framework.

I hope my comments aren't too far away from answering your question.

**Comment by hueniverse** [comment]
The comments above are correct. There isn't anything specific you need to know or be at a particular level. The idea is that you pick the assignments you want to work on based on what you already know and what you want to learn.
